### ISSUE TITLE
Java Out of Memmory Error when creating grapo

### ISSUE THREAD

**Issue by krepaski** [L-Belluomini/OTN-companion#1]

**Comment by krepaski** [comment]
Hey, im getting an Java out of memmory error when im trying to create a graph. Am i doing anything wrong?
![screeny](https://user-images.githubusercontent.com/8652006/163548411-176205ec-5846-43f4-a123-8c047ba43b64.PNG)

**Comment by L-Belluomini** [comment]
hi, you need to specify explicitly how much ram does the vm need to allocate, it should do it automatically but on windows  it tends to go short. to do it set this parameter -Xmx -Xms ( eg java -Xmx2g -Xms2g -cp OTN.jar ..... ) adjust the amount of ram specified to suit your needs. keep in mind that big graphs, will probably crash OTN on the phone https://github.com/L-Belluomini/OTN/issues/4

**Comment by krepaski** [comment]
Hey, thanks for the fast reply, i saw you also implemented a "slow mode" how can i use it? or is it not available now?

**Comment by L-Belluomini** [comment]
slow mode at the moment does not work, and I am not sure it will.. atm I am working on gui version with support for editing the data
