### ISSUE TITLE
area workflow borders check doesn't update straight away

### ISSUE THREAD

**Issue by MightyBakedPotato** [L-Belluomini/OTN-companion#25]
As stated in title, only updates when refreshing the whole pane (such as when changing pane then going back to it)

**Comment by MightyBakedPotato** [comment]
Update: when adding a fresh osm file it doesn't update either

**Comment by L-Belluomini** [comment]
might be a version problem, please check again

**Comment by MightyBakedPotato** [comment]
re-compiled and all, all up to date, still the same
